// ABOUTME: Shows recent investment theses generated by character analysts
// ABOUTME: Displays ticker, name, verdict, and generation date for the 10 most recent theses

import { useState, useEffect } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { Lightbulb, Calendar } from 'lucide-react'

export default function NewTheses() {
    const navigate = useNavigate()
    const [thesesData, setThesesData] = useState({ theses: [], total_count: 0 })
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)

    useEffect(() => {
        const fetchTheses = async () => {
            try {
                setLoading(true)
                const response = await fetch('/api/dashboard/theses')
                if (response.ok) {
                    const data = await response.json()
                    setThesesData(data.recent_theses || { theses: [], total_count: 0 })
                } else {
                    setError('Failed to load theses')
                }
            } catch (err) {
                console.error('Error fetching theses:', err)
                setError('Failed to load theses')
            } finally {
                setLoading(false)
            }
        }

        fetchTheses()
    }, [])

    const theses = thesesData.theses || []
    const totalTodayCount = thesesData.total_count || 0

    return (
        <Card>
            <CardHeader className="p-3 sm:p-4 pb-2">
                <div className="flex items-center justify-between">
                    <CardTitle className="text-base font-medium flex items-center gap-2">
                        <Lightbulb className="h-4 w-4" />
                        New Theses
                    </CardTitle>
                    <Link
                        to="/theses"
                        className="text-xs text-primary hover:underline flex items-center gap-1 transition-colors"
                    >
                        view all
                        <span className="text-[10px]">→</span>
                    </Link>
                </div>
            </CardHeader>
            <CardContent className="p-3 sm:p-6 pt-0 sm:pt-0">
                {loading ? (
                    <div className="space-y-3">
                        {[...Array(5)].map((_, i) => (
                            <Skeleton key={i} className="h-10 w-full" />
                        ))}
                    </div>
                ) : error ? (
                    <div className="h-32 flex items-center justify-center text-sm text-muted-foreground border border-dashed rounded-lg bg-muted/20">
                        {error}
                    </div>
                ) : theses.length > 0 ? (
                    <div className="">
                        {theses.map((item, idx) => (
                            <ThesisRow
                                key={`${item.symbol}-${idx}`}
                                item={item}
                                onClick={() => navigate(`/stock/${item.symbol}?tab=analysis&character=${item.character_id}`)}
                            />
                        ))}
                        {totalTodayCount > theses.length && (
                            <p className="text-xs text-muted-foreground text-center pt-2">
                                +{totalTodayCount - theses.length} more Theses generated today
                            </p>
                        )}
                    </div>
                ) : (
                    <EmptyState />
                )}
            </CardContent>
        </Card>
    )
}

function ThesisRow({ item, onClick }) {
    const verdict = item.verdict || 'UNKNOWN'

    return (
        <button
            onClick={onClick}
            className="w-full flex items-center justify-between py-0.5 px-2 rounded hover:bg-accent transition-colors text-left border-b border-border last:border-0"
        >
            <div className="min-w-0 flex-1 mr-4">
                <div className="flex items-center gap-2">
                    <span className="font-bold text-sm shrink-0">{item.symbol}</span>
                    <span className="text-xs text-muted-foreground truncate max-w-[140px]">
                        {item.name}
                    </span>
                    <Badge variant="secondary" className="text-[9px] h-4 px-1 lowercase py-0 opacity-70">
                        {item.character_id}
                    </Badge>
                </div>
            </div>

            <div className="flex items-center gap-3 shrink-0">
                <span className="text-[10px] text-muted-foreground whitespace-nowrap">
                    {formatDate(item.generated_at)}
                </span>
                <Badge
                    variant="outline"
                    className={`text-[10px] h-5 px-1.5 font-bold ${getVerdictColor(verdict)}`}
                >
                    {verdict}
                </Badge>
            </div>
        </button>
    )
}

function getVerdictColor(verdict) {
    switch (verdict) {
        case 'BUY':
            return 'border-green-500 text-green-500 bg-green-500/10'
        case 'WATCH':
            return 'border-yellow-500 text-yellow-500 bg-yellow-500/10'
        case 'AVOID':
            return 'border-red-500 text-red-500 bg-red-500/10'
        default:
            return 'border-muted text-muted-foreground bg-muted/10'
    }
}

function formatDate(dateStr) {
    if (!dateStr) return ''
    const date = new Date(dateStr.endsWith('Z') ? dateStr : `${dateStr}Z`)
    return date.toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        timeZone: 'America/New_York'
    })
}

function EmptyState() {
    return (
        <div className="flex flex-col items-center justify-center py-8 text-center">
            <Lightbulb className="h-8 w-8 text-muted-foreground mb-2 opacity-20" />
            <p className="text-sm text-muted-foreground">
                No new theses in the last 5 days
            </p>
            <p className="text-xs text-muted-foreground mt-1 max-w-[200px]">
                Theses are generated during daily background runs or when you refresh a stock analysis.
            </p>
        </div>
    )
}
